apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  config.properties: |
    database.host=postgres
    database.port=5432
    database.name=user_service_db
    app.timeout=30
    app.retries=3
