# Install Nginx Ingress Controller
# kubectl apply -f ingress-nginx.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---

# Using Helm is recommended:
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm repo update
# helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace

# Or use kubectl:
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml

# For Minikube:
# minikube addons enable ingress
